### PR TITLE
Fix issue with ResizeObservers and scrollbars

### LINKED ISSUE #1616: Server-initiated resizes don't work in Chrome when "Remote resize" is enabled
**Describe the bug**
When `scaling mode` is set to `remote resize` and resizing the remote screen from the remote side, you get the correct size for a short moment, and then noVNC resizes back to fit your browser viewport.

This should not happen, we should only request a new size from the client-side when the browser window changes.

**To Reproduce**
1. Resize your browser window to a size smaller than 1920x1080
2. Connect using noVNC from Google Chrome
3. Resize the remote screen using `xrandr -s 1920x1080` from a terminal
4. See that the noVNC screen is resized to fit the browser window

**Expected behavior**
I expect to see scrollbars and that the remote screen should be larger than the browser window. This is what happens in Firefox.

**Client (please complete the following information):**
 - OS: Fedora 34
 - Browser: Google Chrome
 - Browser version: 96

**Server (please complete the following information):**
 - noVNC version: 78eda3c0403f82e10a6fe1bcc5f473a9af571474 (latest master)
 - VNC server: TigerVNC
 - WebSocket proxy: websockify

**Additional context**
This is a regression from when we switched to using a `ResizeObserver` instead of listening to the `resize` event. I can reproduce the issue using a9c2ff30b636cf5bb0c5f183302646a5b6ec8481 but not using fcb95821b76e105ed4a7ce4c2c19549c8dbbeb44.

### PR DESCRIPTION
**Pull request by samhed**
Also includes some minor fixups of the unit tests and the removal of an old unnecessary workaround for buggy scrollbars in Google Chrome.

Closes #1616

### CODE REVIEW

File: core/rfb.js [hunk 1]
```diff
@@ -688,6 +688,12 @@ export default class RFB extends EventTargetMixin {
         }
 
         const size = this._screenSize();
+
+        // Don't request the same size we already have
+        if (this._fbWidth === size.w && this._fbHeight === size.h) {
+            return;
+        }
```
Comment (CendioOssman) [inline core/rfb.js:722]: This could in theory be race:y, but I'm not sure it will ever happen in practice.

If you've sent a request but haven't gotten a reply yet, then the values you are checking are stale.

E.g.

1. Start at 100×100
2. Send request to 200×200
3. Before you've gotten a reply, try to resize back to 100×100

This scenario will now break since no request will be sent in 3. The session will be stuck at 200×200 even though 100×100 was the latest proper size.

**Comment by samhed** [comment]
With regards to the "chrome scrollbars"-workaround, it seems to still be needed on Safari 15.1 on macOS 12. Instead of removing it, I have updated the comment now.

File: core/rfb.js (hunk 1 above)
Comment (samhed) [reply core/rfb.js:722]: Good point, I did not consider this. We could save the previous request values and check against those I guess, but I don't think it's worth the added complexity.

I'll remove this change, the gain from it is minimal anyway.

**Comment by samhed** [comment]
I have tested this PR on ..

**Fedora 34:**
- Firefox 95
- Chrome 96

**Android 12:**
- Firefox 95
- Chrome 96
- Edge 96

**Windows 10:**
- Firefox 95
- Chrome 96
- Edge 96

**iPad OS 15.1:**
- Safari 15.1

**macOS 12:**
- Firefox 95
- Chrome 96
- Edge 96
- Safari 15.1

The things I tested was:

- [x] Making size smaller (server initiated)
- [x] Making size larger (server initiated)
- [x] Making size smaller by resizing the browser window
- [x] Making size larger by resizing the browser window
- [x] Scrollbars work when session is too big
- [x] Panning works when session is too big
- [x] Reconnect with a different browser size causes resize
