### PR TITLE
MacOS meta key (⌘) with a different key has unreliable keyup event

### LINKED ISSUE #1695: MacOS meta key (⌘) with a different key has unreliable keyup event
When pressing any combination on MacOS with `⌘` key, keyup event for the second key is not sent.

**To Reproduce**

1. Press `⌘` key.
2. Press and release `V` key.
3. Release `⌘` key.
4. You notice that `V` key is repeatedly written on the screen because keyup event had never been sent.

https://user-images.githubusercontent.com/7534274/192346291-1f4156aa-1a38-44af-8b7f-69b576376719.mov

In logs you can see, that keyup event was not sent, because browser did not trigger that.
image

**Expected behavior**
Since I released the key I would expect that keyup event is sent.

**Client:**
 - OS: MacOS 12.5
 - Browser: Chrome 105, Firefox 104, Safari 15.6

**Server:**
 - noVNC version: from master c101a31520aba083a85edcb2f3269a826471007a, but the part of the code that handles this was not touched for 2 years.
 - VNC server / WebSocket proxy: n/a, because client sends (not or wrong) information.

**Additional context**
Guacamole client fixes exacly this problem [here](https://github.com/apache/guacamole-client/blob/165bd413c0ab9c55b0c0e3614fcb829ef5f8ca95/guacamole-common-js/src/main/webapp/modules/Keyboard.js#L286-L289) by marking those events as unreliable and sends keyup together with keydown:

### PR DESCRIPTION
**Pull request by m1k1o**
Fixes #1695 by auto releasing keys while meta is held down, similar as [apache guacamole's solution](https://github.com/apache/guacamole-client/blob/165bd413c0ab9c55b0c0e3614fcb829ef5f8ca95/guacamole-common-js/src/main/webapp/modules/Keyboard.js#L286-L289).

Must be merged after #1697 or editted based on the outcme of #1696.

### CODE REVIEW

File: core/input/keyboard.js [hunk 1]
```diff
@@ -126,6 +126,15 @@ export default class Keyboard {
             return;
         }
 
+        // If a key is pressed while meta is held down, the keyup will
+        // never be sent in Chrome (bug #108404) and possibly others
+        if (e.metaKey && keysym !== KeyTable.XK_Meta_L && keysym !== KeyTable.XK_Meta_R) {
```
Comment (CendioOssman) [inline core/input/keyboard.js:131]: This is a macOS specific bug, so we want to avoid punishing other platforms.

**Review by CendioOssman — CHANGES_REQUESTED** [review]
Do you think you could look at unit tests for this as well, to make sure this doesn't break in the future? We already have tests for Caps Lock, so you should be able to do something similar.

File: core/input/keyboard.js (hunk 1 above)
Comment (m1k1o) [reply core/input/keyboard.js:131]: Don't know if it could also happen on IOS keyboard. But since the rewrite for both Super-key modifiers is guarded by `browser.isMac() || browser.isIOS()` I'll add it there.

**Comment by m1k1o** [comment]
Moved to `browser.isMac() || browser.isIOS()`, fixed Meta -> Super and added unit tests.

File: core/input/keyboard.js [hunk 2]
```diff
@@ -126,11 +126,20 @@ export default class Keyboard {
...
-        // possibly others).
         if (browser.isMac() || browser.isIOS()) {
+            // If a key is pressed while meta is held down, the keyup will
+            // never be sent in Chrome (bug #108404) and possibly others
+            if (e.metaKey && keysym !== KeyTable.XK_Super_L && keysym !== KeyTable.XK_Super_R) {
+                this._sendKeyEvent(keysym, code, true);
+                this._sendKeyEvent(keysym, code, false);
+                stopEvent(e);
+                return;
+            }
```
Comment (CendioOssman) [inline core/input/keyboard.js:137]: I think it makes more sense to have this next to the other cases where we don't get a keyup event, further down.

**Review by CendioOssman — CHANGES_REQUESTED** [review]
Looks good, thanks! Just a minor code move and we should be good.

Have you had a look at reporting this to the browsers? It would be nice to get the long-term fix rolling as well.

File: core/input/keyboard.js (hunk 2 above)
Comment (m1k1o) [reply core/input/keyboard.js:137]: It must be before shuffling the keys around, because later in code Super_L will be Alt_R and using that in the condition would be even more confusing, I'd say.

Comment (m1k1o) [reply core/input/keyboard.js:137]: Or I could change the condition from `keysym` to `code === 'Meta'`. I try that.

**Comment by m1k1o** [comment]
Moved code to the right place.

**Comment by CendioOssman** [comment]
I think you need to look for `MetaLeft` and `MetaRight` instead. `Meta` is what's stored in `key`, not `code`. Otherwise, I think it looks fine.

**Review by CendioOssman — APPROVED** [review]
Great! Can you just squash the commits together, and then I can go ahead and merge this.

**Comment by m1k1o** [comment]
Ready to merge.

**Comment by CendioOssman** [comment]
Merged now. Thanks for your work!
